# Generated by Django 4.2.1 on 2023-06-08 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HOST_NAME',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namehost', models.CharField(help_text='Введите адрес сайта: ', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='INPUT_INF_HOST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('INT_DATA', models.DateField()),
                ('ID_HOST', models.IntegerField(max_length=10)),
                ('ID_USER', models.IntegerField(max_length=10)),
                ('NAME_HOST', models.TextField(max_length=200)),
                ('PORT_HOST', models.IntegerField(max_length=10)),
            ],
        ),
    ]
