# Generated by Django 4.2.2 on 2023-06-10 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input_inf_host',
            name='ID_HOST',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='input_inf_host',
            name='ID_USER',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='input_inf_host',
            name='NAME_HOST',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='input_inf_host',
            name='PORT_HOST',
            field=models.IntegerField(),
        ),
    ]
