# Generated by Django 4.2.2 on 2023-06-10 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ping', '0002_alter_input_inf_host_id_host_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input_inf_host',
            name='INT_DATA',
            field=models.DateField(auto_now_add=True),
        ),
    ]
