# Generated by Django 4.2.2 on 2023-06-10 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ping', '0003_alter_input_inf_host_int_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input_inf_host',
            name='INT_DATA',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
